from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.text import slugify


class Report(models.Model):
    slug = models.SlugField(default="", blank= True, null = False, db_index=True)
    name = models.CharField(max_length= 20, blank=True)
    fullname = models.CharField(max_length= 100, blank=True)
    author_list = models.CharField(max_length= 500, null=True)
    details = models.TextField(max_length= 1000, null=True, blank=True)
    link = models.CharField(max_length= 100, blank=True, null=True)
    summary = models.TextField(max_length= 1000, null=True, blank=True)
    has_data_table = models.BooleanField(default=False)
    dt_row_n = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(30)])
    dt_col_n = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(15)])
    header_0 = models.CharField(max_length= 20, blank=True, null=True)
    header_1 = models.CharField(max_length= 10, blank=True, null=True)
    header_2 = models.CharField(max_length= 10, blank=True, null=True)
    header_3 = models.CharField(max_length= 10, blank=True, null=True)
    header_4 = models.CharField(max_length= 10, blank=True, null=True)
    header_5 = models.CharField(max_length= 10, blank=True, null=True)
    header_6 = models.CharField(max_length= 10, blank=True, null=True)
    header_7 = models.CharField(max_length= 10, blank=True, null=True)
    header_8 = models.CharField(max_length= 10, blank=True, null=True)
    header_9 = models.CharField(max_length= 10, blank=True, null=True)
    header_10 = models.CharField(max_length= 10, blank=True, null=True)
    header_11 = models.CharField(max_length= 10, blank=True, null=True)
    header_12 = models.CharField(max_length= 10, blank=True, null=True)
    header_13 = models.CharField(max_length= 10, blank=True, null=True)
    header_14 = models.CharField(max_length= 10, blank=True, null=True)
    header_15 = models.CharField(max_length= 10, blank=True, null=True)
    row_1 = models.CharField(max_length= 20, blank=True, null=True)
    row_2 = models.CharField(max_length= 20, blank=True, null=True)
    row_3 = models.CharField(max_length= 20, blank=True, null=True)
    row_4 = models.CharField(max_length= 20, blank=True, null=True)
    row_5 = models.CharField(max_length= 20, blank=True, null=True)
    row_6 = models.CharField(max_length= 20, blank=True, null=True)
    row_7 = models.CharField(max_length= 20, blank=True, null=True)
    row_8 = models.CharField(max_length= 20, blank=True, null=True)
    row_9 = models.CharField(max_length= 20, blank=True, null=True)
    row_10 = models.CharField(max_length= 20, blank=True, null=True)
    row_11 = models.CharField(max_length= 20, blank=True, null=True)
    row_12 = models.CharField(max_length= 20, blank=True, null=True)
    row_13 = models.CharField(max_length= 20, blank=True, null=True)
    row_14 = models.CharField(max_length= 20, blank=True, null=True)
    row_15 = models.CharField(max_length= 20, blank=True, null=True)
    row_16 = models.CharField(max_length= 20, blank=True, null=True)
    row_17 = models.CharField(max_length= 20, blank=True, null=True)
    row_18 = models.CharField(max_length= 20, blank=True, null=True)
    row_19 = models.CharField(max_length= 20, blank=True, null=True)
    row_20 = models.CharField(max_length= 20, blank=True, null=True)
    row_21 = models.CharField(max_length= 20, blank=True, null=True)
    row_22 = models.CharField(max_length= 20, blank=True, null=True)
    row_23 = models.CharField(max_length= 20, blank=True, null=True)
    row_24 = models.CharField(max_length= 20, blank=True, null=True)
    row_25 = models.CharField(max_length= 20, blank=True, null=True)
    row_26 = models.CharField(max_length= 20, blank=True, null=True)
    row_27 = models.CharField(max_length= 20, blank=True, null=True)
    row_28 = models.CharField(max_length= 20, blank=True, null=True)
    row_29 = models.CharField(max_length= 20, blank=True, null=True)
    row_30 = models.CharField(max_length= 20, blank=True, null=True)
    cell_1_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_1_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_2_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_3_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_4_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_5_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_6_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_7_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_8_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_9_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_10_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_11_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_12_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_13_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_14_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_15_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_16_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_17_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_18_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_19_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_20_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_21_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_22_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_23_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_24_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_25_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_26_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_27_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_28_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_29_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_1 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_2 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_3 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_4 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_5 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_6 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_7 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_8 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_9 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_10 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_11 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_12 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_13 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_14 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])
    cell_30_15 = models.IntegerField(default="-1", validators=[MinValueValidator(-1), MaxValueValidator(6)])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.slug} ({self.fullname})" 
    
class Fabric(models.Model):
    slug = models.SlugField(default="", blank=True, null=False, db_index=True)
    name = models.CharField(default="tpr", max_length=20)
    desc = models.CharField(null=True, max_length=100)
    region = models.CharField(null=True, max_length=100)
    calcareous_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    calcareous_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    feldspar_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    feldspar_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    quartz_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    quartz_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    pyroxene_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    pyroxene_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    amphibole_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    amphibole_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    opaque_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    opaque_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    olivine_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    olivine_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    biotite_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    biotite_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    muscovite_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    muscovite_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    epidote_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    epidote_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    igneous_rock_fragments_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    igneous_rock_fragments_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    sedimentary_metasedimentary_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    sedimentary_metasedimentary_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    grog_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    grog_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    garnet_min = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    garnet_max = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    lithics = models.CharField(null=True, max_length=100)
    vitric = models.BooleanField(default=False)
    felsitic = models.BooleanField(default=False)
    microlitic = models.BooleanField(default=False)
    microphaneritic = models.BooleanField(default=False)
    lathwork = models.BooleanField(default=False)
    metavolcanic = models.BooleanField(default=False)
    plutonite = models.BooleanField(default=False)
    amphibolite = models.BooleanField(default=False)
    tectonite = models.BooleanField(default=False)
    argillitic = models.BooleanField(default=False)
    chert = models.BooleanField(default=False)
    quartzite = models.BooleanField(default=False)
    siltstone = models.BooleanField(default=False)
    limeclast = models.BooleanField(default=False)
    comments = models.CharField(null=True, max_length=500)
    refs = models.ManyToManyField(Report, related_name="fabrics", blank=True)
    has_full = models.BooleanField(default=False) 
    has_image = models.BooleanField(default=False) 

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.slug} ({self.desc})"

class Site(models.Model):
    slug = models.SlugField(default="", blank= True, null = False, db_index=True)
    name = models.CharField(max_length= 20)
    island = models.CharField(max_length= 20, null=True)
    lat = models.DecimalField(null=True, max_digits=9, decimal_places=6) 
    lng = models.DecimalField(null=True, max_digits=9, decimal_places=6)
    geonames_id = models.IntegerField(null=True, blank=True)
    open_location_code = models.CharField(null=True, blank=True, max_length=100)
    wikidata_id = models.CharField(null=True, blank=True, max_length=100)
    gettyname = models.CharField(null=True, max_length= 100, blank=True)
    fabrics = models.ManyToManyField(Fabric, related_name="sites", blank=True)
    has_full = models.BooleanField(default=False) 
    has_image = models.BooleanField(default=False)
    island_type = models.CharField(null=True, blank=True, max_length=100)
   
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.island})"

    def thename(self):
        return f"{self.name}" 
    
    @property
    def fabric_string(self):
        fabs = self.fabrics.all()
        fabstring = ''
        for fab in fabs:
            fabstring = fabstring + " (" + fab.name + " " + fab.desc + ")"
        return fabstring
    
class Slide(models.Model):
    name = models.CharField(max_length= 20, db_index=True, unique=True)
    fabric = models.ForeignKey(Fabric, on_delete=models.SET_NULL, null=True, related_name="slides")
    site = models.ForeignKey(Site, on_delete=models.SET_NULL, null=True, blank=True, related_name="slides")
    sherd = models.CharField(null=True, blank=True, max_length=50)
    sherd_origin_site = models.CharField(null=True, max_length=50)
    calcareous = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    feldspar = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    quartz = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    pyroxene = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    amphibole = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    opaque = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    olivine = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    biotite = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    muscovite = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    epidote = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    igneous_rock_fragments = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    sedimentary_metasedimentary = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    grog = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)])
    garnet = models.IntegerField(default="0", validators=[MinValueValidator(0), MaxValueValidator(6)]) 
    lithics = models.CharField(null=True, max_length=100, blank=True)
    vitric = models.BooleanField(default=False)
    felsitic = models.BooleanField(default=False)
    microlitic = models.BooleanField(default=False)
    microphaneritic = models.BooleanField(default=False)
    lathwork = models.BooleanField(default=False)
    metavolcanic = models.BooleanField(default=False)
    plutonite = models.BooleanField(default=False)
    tectonite = models.BooleanField(default=False)
    argillitic = models.BooleanField(default=False)
    chert = models.BooleanField(default=False)
    quartzite = models.BooleanField(default=False)
    siltstone = models.BooleanField(default=False)
    limeclast = models.BooleanField(default=False)
    desc = models.CharField(null=True, max_length=500, blank=True)
    image_name = models.CharField(null=True, max_length=100, blank=True)
    image_omero_id = models.IntegerField(null=True, blank=True)
    full_image_name = models.CharField(null=True, max_length=100, blank=True)
    full_image_omero_id = models.IntegerField(null=True, blank=True)
    full_image_oe_omero_id = models.IntegerField(null=True, blank=True)
    source = models.CharField(default="Dickinson Collection, Bishop Museum", null=True, blank=True, max_length=100)
    refs = models.ManyToManyField(Report, related_name="slides", blank=True)

    def __str__(self):
        return f"{self.name} ({self.sherd})" 

class Wikisite(models.Model):
    slug = models.SlugField(default="", blank= True, null = False, db_index=True)
    name = models.CharField(max_length= 20)
    desc = models.CharField(null=True, max_length= 100, blank=True)
    geoname = models.CharField(null=True, max_length= 100, blank=True)
    gettyname = models.CharField(null=True, max_length= 100, blank=True)
    sites = models.ManyToManyField(Site, related_name="wikisite", blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.desc})"
