# Generated by Django 4.2.3 on 2023-09-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(default='', max_length=50, null=True)),
                ('technique', models.CharField(choices=[('S', 'spiral'), ('SB', 'spiral-beating'), ('SRB', 'spiral-ring-beating'), ('PA', 'paddle-anvil-added'), ('SBU', 'spiral-beating-upside-down'), ('R', 'ring'), ('LBU', 'slab-beating-upside-down'), ('PO', 'paddle-anvil-hand-opened'), ('PC', 'paddle-anvil-coils-added'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20)),
                ('word_cooking', models.CharField(default='', max_length=50, null=True)),
                ('words_other', models.CharField(default='', max_length=100, null=True)),
                ('use_cooking', models.BooleanField(default=True)),
                ('use_storage', models.BooleanField(default=False)),
                ('use_ceremonial', models.BooleanField(default=False)),
                ('use_serving', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
