# Generated by Django 4.2.3 on 2023-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_applique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_combincised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_dentate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_exposedcoil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_finger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_incised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_paint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_position',
            field=models.CharField(choices=[('W', 'whole'), ('N', 'neck'), ('R', 'rim'), ('P', 'plain'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_punctate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='decoration_sculpt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='form_equal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='form_h_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='form_w_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male'), ('B', 'both'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='industry',
            name='language_family',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='temper',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='word_cooking',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='words_other',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
