# Generated by Django 4.2.3 on 2023-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0002_industry_area_industry_decoration_applique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='decoration_combincised',
            new_name='decoration_comb_incised',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='decoration_exposedcoil',
            new_name='decoration_exposed_coil',
        ),
        migrations.AlterField(
            model_name='industry',
            name='language_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
