# Generated by Django 4.2.3 on 2023-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0003_rename_decoration_combincised_industry_decoration_comb_incised_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='desc',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='area',
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('industry', models.ManyToManyField(blank=True, related_name='area', to='pottery.industry')),
            ],
        ),
    ]
