# Generated by Django 4.2.3 on 2023-10-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0004_rename_desc_industry_time_remove_industry_area_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('author_list', models.CharField(max_length=500, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='industry',
            name='time',
        ),
        migrations.AddField(
            model_name='industry',
            name='time_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='time_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='technique',
            field=models.CharField(choices=[('S', 'spiral'), ('SB', 'spiral-beating'), ('SRB', 'spiral-ring-beating'), ('PA', 'paddle-anvil-added'), ('SBU', 'spiral-beating-upside-down'), ('RG', 'ring'), ('LBU', 'slab-beating-upside-down'), ('PO', 'paddle-anvil-hand-opened'), ('PC', 'paddle-anvil-coils-added'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
        migrations.AddField(
            model_name='industry',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='industries', to='pottery.report'),
        ),
    ]
