# Generated by Django 4.2.3 on 2023-10-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0007_remove_industry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='language_superfamily',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
