# Generated by Django 4.2.3 on 2023-10-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0008_industry_language_code_industry_language_superfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
