# Generated by Django 4.2.3 on 2023-10-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0009_alter_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='gender',
            field=models.CharField(choices=[('W', 'women'), ('M', 'men'), ('B', 'both'), ('U', 'unknown')], default='U', max_length=7),
        ),
    ]
