# Generated by Django 4.2.3 on 2023-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0010_alter_industry_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='decoration_paddle',
            field=models.BooleanField(default=False),
        ),
    ]
