# Generated by Django 4.2.3 on 2023-10-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0011_industry_decoration_paddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='language_family',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='technique',
            field=models.CharField(choices=[('S', 'spiral'), ('SB', 'spiral-beating'), ('SRB', 'spiral-ring-beating'), ('SR', 'spiral-ring'), ('PA', 'paddle-anvil-added'), ('SBU', 'spiral-beating-upside-down'), ('RG', 'ring'), ('PR', 'pug-ring-beating'), ('LBU', 'slab-beating-upside-down'), ('PO', 'paddle-anvil-hand-opened'), ('PC', 'paddle-anvil-coils-added'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
    ]
