# Generated by Django 4.2.3 on 2023-08-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('calcareous_min', models.IntegerField()),
                ('calcareous_max', models.IntegerField()),
            ],
        ),
    ]
