# Generated by Django 4.2.3 on 2023-08-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0003_fabric_amphibole_max_fabric_amphibole_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='tpr',
            field=models.CharField(default='tpr', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabric',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
