# Generated by Django 4.2.3 on 2023-08-08 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0005_slide_remove_fabric_tpr_fabric_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrics2.fabric'),
        ),
    ]
