# Generated by Django 4.2.3 on 2023-08-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0006_slide_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
                ('island', models.CharField(max_length=20, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='sherd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrics2.site'),
        ),
    ]
