# Generated by Django 4.2.3 on 2023-08-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0007_site_slide_sherd_slide_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='fabrics2.fabric'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='fabrics2.site'),
        ),
    ]
