# Generated by Django 4.2.3 on 2023-08-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0008_alter_slide_fabric_alter_slide_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
