# Generated by Django 4.2.3 on 2023-08-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0011_remove_slide_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
