# Generated by Django 4.2.3 on 2023-08-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0012_alter_slide_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('author_list', models.CharField(max_length=500, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='argillitic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='chert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='felsitic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='lathwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='limeclast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='metavolcanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='microlitic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='microphaneritic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='plutonite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='quartzite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='siltstone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='tectonite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='vitric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='argillitic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='chert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='felsitic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='lathwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='limeclast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='metavolcanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='microlitic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='microphaneritic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='plutonite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='quartzite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='siltstone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='tectonite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='vitric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric',
            name='refs',
            field=models.ManyToManyField(to='fabrics2.report'),
        ),
        migrations.AddField(
            model_name='slide',
            name='refs',
            field=models.ManyToManyField(to='fabrics2.report'),
        ),
    ]
