# Generated by Django 4.2.3 on 2023-08-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0013_report_fabric_argillitic_fabric_chert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='references',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='references',
        ),
        migrations.AlterField(
            model_name='fabric',
            name='refs',
            field=models.ManyToManyField(related_name='fabrics', to='fabrics2.report'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='refs',
            field=models.ManyToManyField(related_name='slides', to='fabrics2.report'),
        ),
    ]
