# Generated by Django 4.2.3 on 2023-08-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0014_remove_fabric_references_remove_slide_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='fabrics', to='fabrics2.report'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='slides', to='fabrics2.report'),
        ),
    ]
