# Generated by Django 4.2.3 on 2023-08-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0017_fabric_hasfull_fabric_hasimage_site_hasfull_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='hasFull',
            new_name='has_full',
        ),
        migrations.RenameField(
            model_name='fabric',
            old_name='hasImage',
            new_name='has_image',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='hasFull',
            new_name='has_full',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='hasImage',
            new_name='has_image',
        ),
    ]
