# Generated by Django 4.2.3 on 2023-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0018_rename_hasfull_fabric_has_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='amphibolite',
            field=models.BooleanField(default=False),
        ),
    ]
