# Generated by Django 4.2.3 on 2023-11-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0019_fabric_amphibolite'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='geonames_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='open_location_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
