# Generated by Django 4.2.3 on 2024-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0020_site_geonames_id_site_open_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
