# Generated by Django 4.2.3 on 2024-06-05 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0021_report_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cell_1_1',
            field=models.IntegerField(default='-1', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
