# Generated by Django 4.2.3 on 2025-08-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0024_report_dt_col_n_report_dt_row_n_report_header_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_island',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='island_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
