# Generated by Django 4.2.3 on 2025-08-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0025_site_is_island_site_island_type_site_wikidata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='is_island',
        ),
        migrations.AddField(
            model_name='site',
            name='country_wiki',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='island_wiki',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
