# Generated by Django 4.2.3 on 2025-08-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0026_remove_site_is_island_site_country_wiki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
