# Generated by Django 4.2.3 on 2025-08-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0027_site_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='plate',
        ),
        migrations.AddField(
            model_name='site',
            name='island_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='island_group_wiki',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
