# Generated by Django 4.2.3 on 2025-09-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0028_remove_site_plate_site_island_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
