# Generated by Django 4.2.3 on 2025-09-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0029_wikisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='country_wiki',
        ),
        migrations.RemoveField(
            model_name='site',
            name='island_group',
        ),
        migrations.RemoveField(
            model_name='site',
            name='island_group_wiki',
        ),
        migrations.RemoveField(
            model_name='site',
            name='island_wiki',
        ),
        migrations.AddField(
            model_name='wikisite',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='wikisite', to='fabrics2.site'),
        ),
    ]
