# Generated by Django 4.2.3 on 2025-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0030_remove_site_country_wiki_remove_site_island_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikisite',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
