# Generated by Django 4.2.3 on 2025-09-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0031_wikisite_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gettyname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='geoname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='gettyname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
