# Generated by Django 4.2.14 on 2025-10-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0032_site_gettyname_wikisite_geoname_wikisite_gettyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikisite',
            name='mindatname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
