# Generated by Django 4.2.14 on 2025-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0033_wikisite_mindatname'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='macrostrat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='macrostrat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
