# Generated by Django 4.2.14 on 2025-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0034_site_macrostrat_wikisite_lat_wikisite_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='mindatname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
