# Generated by Django 4.2.14 on 2025-10-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0035_site_mindatname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lithology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('mindatname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CeramicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('time_start', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
                ('time_end_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vg_time_end', to='fabrics2.report')),
                ('time_start_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vg_time_start', to='fabrics2.report')),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='lithologies',
            field=models.ManyToManyField(blank=True, related_name='fabrics', to='fabrics2.lithology'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='superfabrics',
            field=models.ManyToManyField(blank=True, related_name='fabrics', to='fabrics2.superfabric'),
        ),
        migrations.AddField(
            model_name='site',
            name='ceramic_periods',
            field=models.ManyToManyField(blank=True, related_name='sites', to='fabrics2.ceramicperiod'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_lithologies',
            field=models.ManyToManyField(blank=True, related_name='at_sites', to='fabrics2.lithology'),
        ),
        migrations.AddField(
            model_name='slide',
            name='ceramic_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='fabrics2.ceramicperiod'),
        ),
    ]
