# Generated by Django 4.2.14 on 2025-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0036_lithology_superfabric_site_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volcano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100, null=True)),
                ('wiki_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('volcanic_region', models.CharField(blank=True, max_length=200, null=True)),
                ('volcano_landform', models.CharField(blank=True, max_length=200, null=True)),
                ('rock_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wikisite',
            name='volcano',
            field=models.ManyToManyField(blank=True, related_name='wikisite', to='fabrics2.volcano'),
        ),
    ]
