# Generated by Django 4.2.14 on 2025-10-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0037_volcano_wikisite_volcano'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='volcano',
            field=models.ManyToManyField(blank=True, related_name='site', to='fabrics2.volcano'),
        ),
    ]
