# Generated by Django 4.2.14 on 2025-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0038_site_volcano'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='sherd_geochem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='sherd_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='sherd_microct',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
