# Generated by Django 4.2.14 on 2025-12-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0039_slide_sherd_geochem_slide_sherd_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='sherd_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
