# Generated by Django 4.2.14 on 2025-12-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0040_slide_sherd_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicperiod',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ceramicperiod',
            name='wikidata',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
