# Generated by Django 4.2.14 on 2025-12-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0041_ceramicperiod_periodo_ceramicperiod_wikidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
