# Generated by Django 4.2.14 on 2025-12-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0042_slide_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='ceramic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='fabrics2.ceramicperiod'),
        ),
    ]
