# Generated by Django 4.2.14 on 2025-12-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0043_alter_slide_ceramic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceramicperiod',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
