# Generated by Django 4.2.14 on 2025-12-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0044_alter_ceramicperiod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfabric',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='superfabric',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
