# Generated by Django 4.2.14 on 2025-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0046_remove_report_cell_10_1_remove_report_cell_10_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfabric',
            name='wiki_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
