# Generated by Django 4.2.14 on 2025-12-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0047_superfabric_wiki_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicperiod',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fabrics2.ceramicperiod'),
        ),
    ]
