# Generated by Django 4.2.14 on 2025-12-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0048_ceramicperiod_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='ceramic_periods',
        ),
        migrations.AddField(
            model_name='wikisite',
            name='ceramic_periods',
            field=models.ManyToManyField(blank=True, related_name='wikisites', to='fabrics2.ceramicperiod'),
        ),
    ]
