# Generated by Django 4.2.14 on 2025-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0049_remove_site_ceramic_periods_wikisite_ceramic_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicperiod',
            name='fabrics',
            field=models.ManyToManyField(blank=True, related_name='ceramic_periods', to='fabrics2.fabric'),
        ),
    ]
