# Generated by Django 4.2.14 on 2026-01-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0050_ceramicperiod_fabrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicperiod',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
