# Generated by Django 4.2.14 on 2026-01-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0051_ceramicperiod_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicperiod',
            name='image_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
