# Generated by Django 4.2.14 on 2026-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0052_ceramicperiod_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='lithologies',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_lithologies',
        ),
        migrations.AddField(
            model_name='site',
            name='dickinson_lithology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='dickinson_lithology',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Lithology',
        ),
    ]
