# Generated by Django 4.2.14 on 2026-07-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0053_remove_fabric_lithologies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('org', models.CharField(blank=True, max_length=200)),
                ('first', models.CharField(blank=True, max_length=200)),
                ('last', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ceramicperiod',
            name='external_link',
            field=models.ManyToManyField(blank=True, related_name='ceramic_periods', to='fabrics2.externallink'),
        ),
        migrations.AddField(
            model_name='site',
            name='external_link',
            field=models.ManyToManyField(blank=True, related_name='sites', to='fabrics2.externallink'),
        ),
        migrations.AddField(
            model_name='wikisite',
            name='external_link',
            field=models.ManyToManyField(blank=True, related_name='wikisites', to='fabrics2.externallink'),
        ),
    ]
