# Generated by Django 4.2.14 on 2026-07-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics2', '0054_externallink_ceramicperiod_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicperiod',
            name='image_attribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ceramicperiod',
            name='image_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ceramicperiod',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
